# Generated by Django 2.2.6 on 2019-12-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetrow',
            name='eeg',
        ),
        migrations.RemoveField(
            model_name='datasetrow',
            name='emg',
        ),
        migrations.AddField(
            model_name='dataset',
            name='size',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetrow',
            name='index',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetrow',
            name='ds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.Dataset'),
        ),
    ]
